Add static relocation and PIC flag handling

diff --git a/gdc b/gdc
--- a/gdc
+++ b/gdc
@@ -45,6 +45,7 @@ want_pthread_link=0
 want_export_dynamic=0
 want_static_libstdcxx=0
 want_static_libgcc=0
+want_static_relocation=0
 
 append_version_flag() {
   local name=$1
@@ -63,8 +64,25 @@ forward_Wl_list() {
   done
 }
 
+add_pic_flag() {
+  local mode=$1
+  if [[ $DC_KIND == dmd ]]; then
+    case $mode in
+      pic) other_args+=( "-fPIC" ) ;;
+      pie) other_args+=( "-fPIE" ) ;;
+    esac
+  else
+    case $mode in
+      pic) other_args+=( "-relocation-model=pic" ) ;;
+      pie) other_args+=( "-relocation-model=pie" ) ;;
+    esac
+  fi
+}
+
 while (( $# )); do
-  arg=$1; shift
+  arg=$1
+  shift
+
   if [[ $arg == -x ]]; then
     (( $# )) && shift
     continue
@@ -82,6 +100,7 @@ while (( $# )); do
       out=$1
       shift
       ;;
+
     -o*)
       out=${arg#-o}
       ;;
@@ -93,6 +112,7 @@ while (( $# )); do
     -g)
       opt_dbg_flags+=( "$arg" )
       ;;
+
     -O|-O0|-O1|-O2|-O3)
       if [[ $DC_KIND == dmd ]]; then
         opt_dbg_flags+=( "-O" )
@@ -111,6 +131,7 @@ while (( $# )); do
     -fversion=*)
       append_version_flag "${arg#*=}"
       ;;
+
     -D*)
       append_version_flag "${arg#-D}"
       ;;
@@ -119,20 +140,30 @@ while (( $# )); do
       other_args+=( "-release" )
       ;;
 
-    -fPIE|-fpie)
-      other_args+=( "-fPIC" )
+    -fPIC|-fpic)
+      add_pic_flag pic
       ;;
-    -fno-PIE|-fno-pie)
+
+    -fPIE|-fpie)
+      add_pic_flag pie
+      ;;
+
+    -fno-PIC|-fno-pic|-fno-PIE|-fno-pie)
+      want_static_relocation=1
       want_no_pie=1
       ;;
+
     -pie)
       other_args+=( "-L-pie" )
       ;;
+
     -no-pie)
       want_no_pie=1
+      want_static_relocation=1
       ;;
+
     -rdynamic)
-      want_export_dynamic=1   # later becomes -L--export-dynamic
+      want_export_dynamic=1
       ;;
 
     -fno-exceptions|-fno-rtti|--fno-exceptions|--fno-rtti)
@@ -151,26 +182,34 @@ while (( $# )); do
       other_args+=( "-mtriple" "$1" )
       shift
       ;;
+
     -target=*)
       other_args+=( "-mtriple=${arg#*=}" )
       ;;
+
     -W)
       other_args+=( "-wi" )
       ;;
+
     -Wall|-Wextra)
       other_args+=( "-wi" )
       ;;
+
     -Werror)
       other_args+=( "-w" )
       ;;
+
     -Wdeprecated)
       other_args+=( "-dw" )
       ;;
+
     -Wno-*)
       ;;
+
     -Wl,*)
       forward_Wl_list "${arg#-Wl,}"
       ;;
+
     -W*)
       ;;
 
@@ -178,10 +217,21 @@ while (( $# )); do
       ;;
 
     -MT)
+      if [[ $# -eq 0 ]]; then
+        echo "gdc: error: missing target after '-MT'" >&2
+        exit 1
+      fi
+      echo "gdc: warning: unsupported flag '-MT' ignored" >&2
+      shift
+      ;;
+
+    -MT*)
       echo "gdc: warning: unsupported flag '-MT' ignored" >&2
       ;;
+
     -MMD|-MD|--MD|-MP|--MP)
       ;;
+
     -MF)
       if [[ $# -eq 0 ]]; then
         echo "gdc: error: missing filename after '-MF'" >&2
@@ -198,6 +248,7 @@ while (( $# )); do
         echo "gdc: warning: '-shared-libphobos' unsupported for dmd; ignoring" >&2
       fi
       ;;
+
     -static-libphobos)
       if [[ $DC_KIND == ldc ]]; then
         other_args+=( "-link-defaultlib-shared=false" )
@@ -209,6 +260,7 @@ while (( $# )); do
     -static-libstdc++)
       want_static_libstdcxx=1
       ;;
+
     -static-libgcc)
       want_static_libgcc=1
       ;;
@@ -216,6 +268,7 @@ while (( $# )); do
     -static|-shared)
       other_args+=( "-L${arg}" )
       ;;
+
     -L*|-l*)
       other_args+=( "-L${arg}" )
       ;;
@@ -230,6 +283,10 @@ while (( $# )); do
   esac
 done
 
+if (( want_static_relocation )) && [[ $DC_KIND == ldc ]]; then
+  other_args+=( "-relocation-model=static" )
+fi
+
 get_default_out() {
   if (( ${#other_args[@]} )); then
     for src in "${other_args[@]}"; do
@@ -238,7 +295,7 @@ get_default_out() {
         if (( compile_only )); then
           printf '%s.o\n' "${bn%.*}"
         else
-          printf '%s\n'   "${bn%.*}"
+          printf '%s\n' "${bn%.*}"
         fi
         return
       fi
@@ -265,9 +322,9 @@ else
   (( ${#opt_dbg_flags[@]} )) && cmd+=( "${opt_dbg_flags[@]}" )
   (( ${#other_args[@]} ))    && cmd+=( "${other_args[@]}" )
 
-  (( want_no_pie ))           && cmd+=( "-L-no-pie" )
-  (( want_pthread_link ))     && cmd+=( "-L-pthread" )
-  (( want_export_dynamic ))   && cmd+=( "-L--export-dynamic" )
+  (( want_no_pie ))         && cmd+=( "-L-no-pie" )
+  (( want_pthread_link ))   && cmd+=( "-L-pthread" )
+  (( want_export_dynamic )) && cmd+=( "-L--export-dynamic" )
 
   if (( want_static_libstdcxx )); then
     cmd+=( "-L-Bstatic" "-L-lstdc++" "-L-Bdynamic" )
